spring:
  application:
    name: blog
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 1083344129@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: igjtkwxsdephiaed
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

#

mybatis-plus:
  type-aliases-package: com.miku.entity # 别名扫描包
  ##配置mybatisplus输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: cc_
      ##这三个配置 是用于逻辑删除的
      ##逻辑删除的字段
      logic-delete-field: isValid
      ##逻辑删除的值
      logic-delete-value: 0
      ##逻辑不删除的值
      logic-not-delete-value: 1
logging:
  level:
    com.hmdp: debug

