spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.159.252.234:3306/testblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://139.159.252.234:3306/testblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: testBlog
    password: miku
server:
  port: 9000
mybatis-plus:
  type-aliases-package: com.miku.entity # 别名扫描包
  ##配置mybatisplus输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: cc_
logging:
  level:
    com.hmdp: debug
miku:
  uploadurl: http://139.159.252.234:8083/upload/
  localurl: /www/server/nginx/html/image/