spring:
  application:
    name: blog
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.miku.entity # 别名扫描包
  ##配置mybatisplus输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: cc_
      ##这三个配置 是用于逻辑删除的
      ##逻辑删除的字段
      logic-delete-field: isValid
      ##逻辑删除的值
      logic-delete-value: 0
      ##逻辑不删除的值
      logic-not-delete-value: 1
logging:
  level:
    com.hmdp: debug
