spring:
  application:
    name: blog

  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 1083344129@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: nacjsulkacfbgadh
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

#
mybatis-plus:
  type-aliases-package: com.miku.entity # 别名扫描包
  ##配置mybatisplus输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: cc_
      ##这三个配置 是用于逻辑删除的
      ##逻辑删除的字段
      logic-delete-field: isValid
      ##逻辑删除的值
      logic-delete-value: 0
      ##逻辑不删除的值
      logic-not-delete-value: 1
  mapper-locations: classpath:mapper/xml/*.xml
logging:
  level:
    com.blog: debug
chatgpt:
  token: sk-Am9q8vNvAaPNy2ZGTd8UltyTQFGloD16EfLKuZqg7For6gyC
  proxy-host: https://api.chatanywhere.com.cn
  session-expiration-time: 300
  #proxy-port: api.chatanywhere.com.cn#
  #base-url: https://api.chatanywhere.com.cn
myconfig:
  salt: cywltxdy
cc:
  miku:
    avatar: 127.0.0.1:8085/0.jpg
forbidden:
  words:
    filepath: classpath:forbidden_words.txt
server:
  servlet:
    context-path: /api
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3