### dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.16.124:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: miku
    password: 2270398619
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最小空闲
        min-idle: 0
        # 最大空闲
        max-idle: 5
        #最大阻塞等待散件(负数表示没限制)
        max-wait: -1
        #最大连接数
        max-active: 8
    #链接过期时间
    timeout: 10000
server:
  port: 9001
miku:
  uploadurl: http://localhost:8085/img/
  localurl: G:/a_vue/nginx-1.23.4/html/img/